apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karma.fullname" . }}
  labels:
    {{- include "karma.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "karma.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "karma.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: karma
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ALERTMANAGER_URI
              value: {{ .Values.alertmanager.uri | quote }}
            - name: ALERTMANAGER_NAME
              value: {{ .Values.alertmanager.name | quote }}
            - name: ALERTMANAGER_PROXY
              value: "true"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

